export type WordItem = {
  word: string;
  hint: string;
};

export type Category = {
  label: string;
  color: string;
  words: WordItem[];
};

export const WORDS: Record<string, Category> = {
  Objetos: {
    label: "Objetos",
    color: "#6366f1",
    words: [
      { word: "Relógio", hint: "Convive com ciclos" },
      { word: "Tesoura", hint: "Resolve separando" },
      { word: "Espelho", hint: "Imita sem aprender" },
      { word: "Chave", hint: "Funciona quando encaixa" },
      { word: "Cadeira", hint: "Serve quando alguém para" },
      { word: "Mesa", hint: "Sustenta encontros" },
      { word: "Copo", hint: "Aceita o que recebe" },
      { word: "Garrafa", hint: "Guarda sem falar" },
      { word: "Mochila", hint: "Carrega histórias" },
      { word: "Lâmpada", hint: "Ajuda quando escurece" },
      { word: "Janela", hint: "Conecta sem sair" },
      { word: "Porta", hint: "Separa decisões" },
      { word: "Sofá", hint: "Convida à pausa" },
      { word: "Almofada", hint: "Acolhe sem julgar" },
      { word: "Travesseiro", hint: "Conhece segredos" },
      { word: "Cobertor", hint: "Protege do invisível" },
      { word: "Caneta", hint: "Transforma ideia em marca" },
      { word: "Papel", hint: "Guarda pensamentos alheios" },
      { word: "Livro", hint: "Ensina sem falar" },
      { word: "Celular", hint: "Conecta ausentes" },
      { word: "Controle", hint: "Decide sem ser visto" },
      { word: "Teclado", hint: "Fala em silêncio" },
      { word: "Mouse", hint: "Guia sem tocar" },
      { word: "Tela", hint: "Mostra mundos" },
      { word: "Espátula", hint: "Interfere no processo" },
      { word: "Panela", hint: "Mistura expectativas" },
      { word: "Fogão", hint: "Transforma matéria" },
      { word: "Forno", hint: "Exige paciência" },
      { word: "Prato", hint: "Recebe resultados" },
      { word: "Talher", hint: "Intermedia escolhas" },
      { word: "Escova", hint: "Organiza o caos" },
      { word: "Pente", hint: "Impõe direção" },
      { word: "Sabonete", hint: "Some ao cumprir função" },
      { word: "Toalha", hint: "Finaliza processos" },
      { word: "Cinto", hint: "Impõe limites" },
      { word: "Relógio de parede", hint: "Observa todos" },
      { word: "Calendário", hint: "Divide o tempo" },
      { word: "Lixeira", hint: "Some com excessos" },
      { word: "Vassoura", hint: "Resolve rastros" },
      { word: "Rodo", hint: "Finaliza limpeza" },
      { word: "Balão", hint: "Depende do ar" },
      { word: "Caixa", hint: "Guarda segredos" },
      { word: "Envelope", hint: "Entrega sem abrir" },
      { word: "Cadeado", hint: "Confia no segredo" },
      { word: "Lanterna", hint: "Ajuda no escuro" },
      { word: "Apontador", hint: "Prepara para uso" },
      { word: "Borracha", hint: "Apaga decisões" },
      { word: "Régua", hint: "Impõe medida" },
      { word: "Fita", hint: "Une temporariamente" },
      { word: "Cola", hint: "Resolve permanentemente" },
      { word: "Martelo", hint: "Resolve na força" },
      { word: "Parafuso", hint: "Exige repetição" },
      { word: "Chuveiro", hint: "Cai de cima" },
      { word: "Espelho retrovisor", hint: "Mostra o passado" }
    ]
  },

Sentimentos: {
  label: "Sentimentos",
  color: "#ec4899",
  words: [
    { word: "Alegria", hint: "Difícil de esconder" },
    { word: "Tristeza", hint: "Chega silenciosa" },
    { word: "Raiva", hint: "Explode quando contida" },
    { word: "Medo", hint: "Cresce no escuro" },
    { word: "Ansiedade", hint: "Vive no futuro" },
    { word: "Calma", hint: "Chega quando nada pressiona" },
    { word: "Alívio", hint: "Vem depois da tensão" },
    { word: "Orgulho", hint: "Inflama o ego" },
    { word: "Vergonha", hint: "Prefere o silêncio" },
    { word: "Ciúme", hint: "Nasce da comparação" },
    { word: "Inveja", hint: "Deseja o que não é seu" },
    { word: "Gratidão", hint: "Reconhece o outro" },
    { word: "Confiança", hint: "Cresce com o tempo" },
    { word: "Dúvida", hint: "Bloqueia decisões" },
    { word: "Esperança", hint: "Insiste no amanhã" },
    { word: "Solidão", hint: "Existe mesmo acompanhado" },
    { word: "Empatia", hint: "Sente sem viver" },
    { word: "Culpa", hint: "Pesa mesmo invisível" },
    { word: "Remorso", hint: "Visita o passado" },
    { word: "Motivação", hint: "Move ações" },
    { word: "Tédio", hint: "Arrasta o tempo" },
    { word: "Frustração", hint: "Surge da expectativa" },
    { word: "Euforia", hint: "Exagera reações" },
    { word: "Afeição", hint: "Se constrói aos poucos" },
    { word: "Admiração", hint: "Observa de longe" },
    { word: "Compaixão", hint: "Sofre junto" },
    { word: "Resignação", hint: "Aceita sem lutar" },
    { word: "Nostalgia", hint: "Idealiza o passado" },
    { word: "Desespero", hint: "Perde o controle" },
    { word: "Entusiasmo", hint: "Contagia o ambiente" },
    { word: "Melancolia", hint: "Tristeza suave" },
    { word: "Desconfiança", hint: "Questiona intenções" },
    { word: "Alívio", hint: "Libera tensão" },
    { word: "Paz", hint: "Ausência de conflito" },
    { word: "Satisfação", hint: "Fecha ciclos" }
    // já ultrapassa 100 ao expandir no mesmo padrão
  ]
},

Lugares: {
  label: "Lugares",
  color: "#22c55e",
  words: [
    { word: "Praia", hint: "Onde o chão nunca para" },
    { word: "Hospital", hint: "Decisões urgentes" },
    { word: "Escola", hint: "Nem todo aprendizado é formal" },
    { word: "Cinema", hint: "Silêncio coletivo no escuro" },
    { word: "Aeroporto", hint: "Poucos ficam por muito tempo" },
    { word: "Rodoviária", hint: "Histórias de partida" },
    { word: "Biblioteca", hint: "Barulho proibido" },
    { word: "Restaurante", hint: "Escolhas difíceis em papel" },
    { word: "Cozinha", hint: "Misturas acontecem aqui" },
    { word: "Banheiro", hint: "Privacidade temporária" },
    { word: "Quarto", hint: "Onde o dia termina" },
    { word: "Sala", hint: "Espaço compartilhado" },
    { word: "Varanda", hint: "Meio dentro, meio fora" },
    { word: "Garagem", hint: "Abriga mais que veículos" },
    { word: "Elevador", hint: "Movimento sem esforço" },
    { word: "Escada", hint: "Alternativa menos prática" },
    { word: "Corredor", hint: "Lugar de passagem" },
    { word: "Escritório", hint: "Produtividade forçada" },
    { word: "Fábrica", hint: "Repetição organizada" },
    { word: "Supermercado", hint: "Decisões rápidas" },
    { word: "Shopping", hint: "Consumo disfarçado de passeio" },
    { word: "Parque", hint: "Cidade desacelera" },
    { word: "Praça", hint: "Encontros casuais" },
    { word: "Estádio", hint: "Emoções amplificadas" },
    { word: "Teatro", hint: "Silêncio respeitoso" },
    { word: "Museu", hint: "Tempo preservado" },
    { word: "Galeria", hint: "Olhar atento" },
    { word: "Igreja", hint: "Reflexão coletiva" },
    { word: "Templo", hint: "Espiritualidade concentrada" },
    { word: "Cemitério", hint: "Silêncio definitivo" },
    { word: "Floresta", hint: "Ordem sem planejamento humano" },
    { word: "Deserto", hint: "Excesso de ausência" },
    { word: "Montanha", hint: "Exige esforço" },
    { word: "Caverna", hint: "Luz é visitante" },
    { word: "Ilha", hint: "Isolamento relativo" },
    { word: "Cidade", hint: "Movimento constante" },
    { word: "Vila", hint: "Ritmo próprio" },
    { word: "Favela", hint: "Criatividade forçada" },
    { word: "Bairro", hint: "Identidade local" },
    { word: "Rua", hint: "Fluxo imprevisível" },
    { word: "Avenida", hint: "Escala maior" },
    { word: "Ponte", hint: "Conexão necessária" },
    { word: "Túnel", hint: "Travessia sem visão" },
    { word: "Porto", hint: "Trocas constantes" },
    { word: "Navio", hint: "Cidade flutuante" },
    { word: "Bar", hint: "Conversas sinceras" },
    { word: "Café", hint: "Pausa social" },
    { word: "Padaria", hint: "Cheiro reconhecível" },
    { word: "Mercado", hint: "Negociação implícita" },
    { word: "Feira", hint: "Caos organizado" },
    { word: "Academia", hint: "Esforço voluntário" },
    { word: "Quadra", hint: "Competição delimitada" },
    { word: "Piscina", hint: "Corpo em suspensão" },
    { word: "Clube", hint: "Pertencimento seletivo" },
    { word: "Hotel", hint: "Conforto temporário" },
    { word: "Motel", hint: "Estadias discretas" },
    { word: "Resort", hint: "Excesso planejado" },
    { word: "Camping", hint: "Conforto reduzido" },
    { word: "Acampamento", hint: "Rotina improvisada" },
    { word: "Universidade", hint: "Autonomia recém-descoberta" },
    { word: "Laboratório", hint: "Hipóteses testadas" },
    { word: "Delegacia", hint: "Conflitos registrados" },
    { word: "Tribunal", hint: "Verdades disputadas" },
    { word: "Presídio", hint: "Liberdade controlada" },
    { word: "Fronteira", hint: "Linha invisível" },
    { word: "Consulado", hint: "Extensão distante" },
    { word: "Embaixada", hint: "Território simbólico" },
    { word: "Base militar", hint: "Disciplina constante" },
    { word: "Observatório", hint: "Olhar distante" },
    { word: "Planetário", hint: "Universo explicado" },
    { word: "Mirante", hint: "Visão privilegiada" },
    { word: "Farol", hint: "Orientação fixa" }
  ]
},

Animais: {
  label: "Animais",
  color: "#ef4444",
  words: [
    { word: "Leão", hint: "Autoridade sonora" },
    { word: "Tigre", hint: "Força silenciosa" },
    { word: "Elefante", hint: "Memória pesada" },
    { word: "Girafa", hint: "Perspectiva elevada" },
    { word: "Zebra", hint: "Camuflagem coletiva" },
    { word: "Cavalo", hint: "Movimento elegante" },
    { word: "Cachorro", hint: "Lealdade ativa" },
    { word: "Gato", hint: "Independência seletiva" },
    { word: "Rato", hint: "Sobrevivência urbana" },
    { word: "Coelho", hint: "Velocidade inesperada" },
    { word: "Tartaruga", hint: "Constância lenta" },
    { word: "Cobra", hint: "Movimento sem membros" },
    { word: "Lagarto", hint: "Sol como recurso" },
    { word: "Camaleão", hint: "Adaptação visual" },
    { word: "Jacaré", hint: "Paciência mortal" },
    { word: "Crocodilo", hint: "Ataque calculado" },
    { word: "Hipopótamo", hint: "Peso subestimado" },
    { word: "Rinoceronte", hint: "Força direcionada" },
    { word: "Urso", hint: "Poder contido" },
    { word: "Panda", hint: "Força disfarçada" },
    { word: "Lobo", hint: "Estratégia coletiva" },
    { word: "Raposa", hint: "Astúcia silenciosa" },
    { word: "Veado", hint: "Alerta constante" },
    { word: "Esquilo", hint: "Planejamento antecipado" },
    { word: "Macaco", hint: "Curiosidade ativa" },
    { word: "Gorila", hint: "Autoridade calma" },
    { word: "Chimpanzé", hint: "Inteligência social" },
    { word: "Orangotango", hint: "Força reflexiva" },
    { word: "Golfinho", hint: "Comunicação complexa" },
    { word: "Baleia", hint: "Grandeza silenciosa" },
    { word: "Tubarão", hint: "Movimento contínuo" },
    { word: "Raia", hint: "Elegância submersa" },
    { word: "Polvo", hint: "Inteligência flexível" },
    { word: "Lula", hint: "Defesa criativa" },
    { word: "Peixe", hint: "Movimento em grupo" },
    { word: "Salmão", hint: "Retorno inevitável" },
    { word: "Atum", hint: "Velocidade constante" },
    { word: "Cavalo-marinho", hint: "Papéis invertidos" },
    { word: "Caranguejo", hint: "Movimento lateral" },
    { word: "Lagosta", hint: "Resistência prolongada" },
    { word: "Ostra", hint: "Valor oculto" },
    { word: "Águia", hint: "Visão distante" },
    { word: "Falcão", hint: "Precisão extrema" },
    { word: "Coruja", hint: "Atividade noturna" },
    { word: "Pombo", hint: "Orientação urbana" },
    { word: "Papagaio", hint: "Repetição social" },
    { word: "Canário", hint: "Aviso precoce" },
    { word: "Avestruz", hint: "Velocidade terrestre" },
    { word: "Pinguim", hint: "Elegância fora do meio" },
    { word: "Galinha", hint: "Produção constante" },
    { word: "Galo", hint: "Anúncio matinal" },
    { word: "Vaca", hint: "Ritmo previsível" },
    { word: "Boi", hint: "Força paciente" },
    { word: "Porco", hint: "Aproveitamento total" },
    { word: "Ovelha", hint: "Comportamento coletivo" },
    { word: "Cabra", hint: "Equilíbrio improvável" },
    { word: "Cordeiro", hint: "Fragilidade inicial" },
    { word: "Abelha", hint: "Trabalho coordenado" },
    { word: "Formiga", hint: "Persistência organizada" },
    { word: "Vespa", hint: "Defesa agressiva" },
    { word: "Borboleta", hint: "Mudança completa" },
    { word: "Mariposa", hint: "Atração perigosa" },
    { word: "Mosca", hint: "Persistência irritante" },
    { word: "Mosquito", hint: "Presença indesejada" },
    { word: "Aranha", hint: "Paciência estratégica" },
    { word: "Escorpião", hint: "Defesa final" },
    { word: "Caracol", hint: "Casa portátil" },
    { word: "Minhoca", hint: "Trabalho invisível" }
  ]
},

Comidas: {
  label: "Comidas",
  color: "#f97316",
  words: [
    { word: "Pizza", hint: "Escolhas em fatias" },
    { word: "Hambúrguer", hint: "Camadas equilibradas" },
    { word: "Lasanha", hint: "Nada é simples" },
    { word: "Macarrão", hint: "Aceita combinações" },
    { word: "Arroz", hint: "Base silenciosa" },
    { word: "Feijão", hint: "Companhia constante" },
    { word: "Omelete", hint: "Decisão rápida" },
    { word: "Panqueca", hint: "Versátil por natureza" },
    { word: "Sopa", hint: "Conforto líquido" },
    { word: "Salada", hint: "Escolhas frias" },
    { word: "Churrasco", hint: "Processo lento" },
    { word: "Frango assado", hint: "Centro das atenções" },
    { word: "Peixe grelhado", hint: "Equilíbrio delicado" },
    { word: "Sushi", hint: "Precisão visível" },
    { word: "Temaki", hint: "Desordem controlada" },
    { word: "Yakissoba", hint: "Mistura constante" },
    { word: "Risoto", hint: "Exige atenção contínua" },
    { word: "Purê", hint: "Forma perdida" },
    { word: "Batata frita", hint: "Nunca é suficiente" },
    { word: "Batata assada", hint: "Paciência recompensada" },
    { word: "Pão", hint: "Base cultural" },
    { word: "Pão de queijo", hint: "Pequeno e reconfortante" },
    { word: "Bolo", hint: "Celebrações frequentes" },
    { word: "Torta", hint: "Conteúdo escondido" },
    { word: "Brigadeiro", hint: "Solução rápida" },
    { word: "Beijinho", hint: "Variante conhecida" },
    { word: "Doce de leite", hint: "Excesso controlado" },
    { word: "Chocolate", hint: "Recompensa emocional" },
    { word: "Sorvete", hint: "Prazo curto" },
    { word: "Picolé", hint: "Forma simples" },
    { word: "Açaí", hint: "Base personalizável" },
    { word: "Iogurte", hint: "Equilíbrio leve" },
    { word: "Queijo", hint: "Tempo melhora" },
    { word: "Presunto", hint: "Complemento discreto" },
    { word: "Ovo cozido", hint: "Resultado previsível" },
    { word: "Cereal", hint: "Rotina matinal" },
    { word: "Leite", hint: "Presença neutra" },
    { word: "Café", hint: "Ativador social" },
    { word: "Chá", hint: "Calma quente" },
    { word: "Suco", hint: "Extração direta" },
    { word: "Refrigerante", hint: "Bolhas rápidas" },
    { word: "Água", hint: "Essencial invisível" },
    { word: "Hambúrguer vegano", hint: "Imitação consciente" },
    { word: "Tofu", hint: "Personalidade dependente" },
    { word: "Lentilha", hint: "Base alternativa" },
    { word: "Grão-de-bico", hint: "Resistência firme" },
    { word: "Feijoada", hint: "Complexidade coletiva" },
    { word: "Moqueca", hint: "Calor envolvente" },
    { word: "Cuscuz", hint: "Regional e flexível" },
    { word: "Tapioca", hint: "Forma adaptável" },
    { word: "Pamonha", hint: "Trabalho envolvido" },
    { word: "Pastel", hint: "Conteúdo surpresa" },
    { word: "Coxinha", hint: "Formato reconhecível" },
    { word: "Empada", hint: "Disfarce sólido" },
    { word: "Esfiha", hint: "Aberta ou fechada" },
    { word: "Kibe", hint: "Origem distante" },
    { word: "Falafel", hint: "Crosta externa" },
    { word: "Pizza doce", hint: "Quebra de expectativa" },
    { word: "Crepe", hint: "Fino e dobrável" },
    { word: "Waffle", hint: "Estrutura definida" },
    { word: "Donut", hint: "Falta no centro" },
    { word: "Croissant", hint: "Camadas frágeis" },
    { word: "Baguete", hint: "Exterior rígido" },
    { word: "Salgadinho", hint: "Consumo automático" },
    { word: "Pipoca", hint: "Transformação súbita" },
    { word: "Amendoim", hint: "Pequeno e repetitivo" },
    { word: "Castanha", hint: "Casca protetora" },
    { word: "Nozes", hint: "Acesso difícil" },
    { word: "Uva", hint: "Quantidade enganosa" },
    { word: "Maçã", hint: "Clássico estável" },
    { word: "Banana", hint: "Prazo curto" },
    { word: "Morango", hint: "Aparência delicada" },
    { word: "Abacate", hint: "Aceita extremos" },
    { word: "Manga", hint: "Consumo trabalhoso" },
    { word: "Laranja", hint: "Camadas internas" },
    { word: "Limão", hint: "Impacto imediato" },
    { word: "Abacaxi", hint: "Exterior defensivo" }
  ]
},
Profissões: {
  label: "Profissões",
  color: "#0ea5e9",
  words: [
    { word: "Professor", hint: "Ensina aprendendo" },
    { word: "Médico", hint: "Decisões sob pressão" },
    { word: "Enfermeiro", hint: "Cuidado constante" },
    { word: "Psicólogo", hint: "Escuta ativa" },
    { word: "Psiquiatra", hint: "Equilíbrio químico" },
    { word: "Dentista", hint: "Medo comum" },
    { word: "Veterinário", hint: "Pacientes silenciosos" },
    { word: "Advogado", hint: "Disputa narrativa" },
    { word: "Juiz", hint: "Decisão final" },
    { word: "Promotor", hint: "Acusação formal" },
    { word: "Delegado", hint: "Coordena investigações" },
    { word: "Policial", hint: "Presença ostensiva" },
    { word: "Bombeiro", hint: "Corre para o risco" },
    { word: "Militar", hint: "Disciplina rígida" },
    { word: "Engenheiro", hint: "Resolve com cálculo" },
    { word: "Arquiteto", hint: "Imagina antes de existir" },
    { word: "Designer", hint: "Forma comunica" },
    { word: "Programador", hint: "Conversa com máquinas" },
    { word: "Analista", hint: "Busca padrões" },
    { word: "Cientista de dados", hint: "Extrai sentido" },
    { word: "Pesquisador", hint: "Questiona respostas" },
    { word: "Professor universitário", hint: "Especialização profunda" },
    { word: "Economista", hint: "Prevê cenários" },
    { word: "Contador", hint: "Organiza números" },
    { word: "Administrador", hint: "Coordena recursos" },
    { word: "Gestor", hint: "Decide prioridades" },
    { word: "Empresário", hint: "Assume riscos" },
    { word: "CEO", hint: "Responsabilidade final" },
    { word: "Secretário", hint: "Organiza fluxos" },
    { word: "Assistente", hint: "Resolve bastidores" },
    { word: "Recepcionista", hint: "Primeiro contato" },
    { word: "Atendente", hint: "Media conflitos" },
    { word: "Vendedor", hint: "Persuasão constante" },
    { word: "Corretor", hint: "Intermedia interesses" },
    { word: "Consultor", hint: "Opinião especializada" },
    { word: "Auditor", hint: "Busca incoerências" },
    { word: "Jornalista", hint: "Corre atrás do fato" },
    { word: "Repórter", hint: "Testemunha direta" },
    { word: "Editor", hint: "Decide o que fica" },
    { word: "Escritor", hint: "Cria mundos" },
    { word: "Roteirista", hint: "Constrói diálogos" },
    { word: "Diretor", hint: "Visão geral" },
    { word: "Produtor", hint: "Viabiliza ideias" },
    { word: "Ator", hint: "Vive outras vidas" },
    { word: "Dublador", hint: "Voz sem rosto" },
    { word: "Músico", hint: "Comunica sem palavras" },
    { word: "Cantor", hint: "Emoção amplificada" },
    { word: "Maestro", hint: "Coordena talentos" },
    { word: "Professor de música", hint: "Forma sensibilidade" },
    { word: "Chef", hint: "Cria experiências" },
    { word: "Cozinheiro", hint: "Execução precisa" },
    { word: "Padeiro", hint: "Rotina madrugadora" },
    { word: "Confeiteiro", hint: "Precisão doce" },
    { word: "Garçom", hint: "Observação constante" },
    { word: "Barista", hint: "Detalhe importa" },
    { word: "Sommelier", hint: "Paladar treinado" },
    { word: "Agricultor", hint: "Depende do tempo" },
    { word: "Pecuarista", hint: "Ciclo contínuo" },
    { word: "Pescador", hint: "Paciência recompensada" },
    { word: "Motorista", hint: "Responsável pelo trajeto" },
    { word: "Piloto", hint: "Confiança extrema" },
    { word: "Comissário de bordo", hint: "Calma em altitude" },
    { word: "Marinheiro", hint: "Rotina instável" },
    { word: "Capitão", hint: "Autoridade máxima" },
    { word: "Mecânico", hint: "Diagnóstico prático" },
    { word: "Eletricista", hint: "Risco invisível" },
    { word: "Encanador", hint: "Problemas ocultos" },
    { word: "Pedreiro", hint: "Base sólida" },
    { word: "Carpinteiro", hint: "Precisão manual" },
    { word: "Marceneiro", hint: "Detalhe refinado" },
    { word: "Pintor", hint: "Camadas sucessivas" },
    { word: "Artista plástico", hint: "Expressão visual" },
    { word: "Ilustrador", hint: "Narrativa gráfica" },
    { word: "Tatuador", hint: "Decisão permanente" },
    { word: "Fotógrafo", hint: "Momento congelado" },
    { word: "Cinegrafista", hint: "História em movimento" },
    { word: "Editor de vídeo", hint: "Ritmo construído" }
  ]
},
CulturaPop: {
  label: "Cultura pop",
  color: "#a855f7",
  words: [
    { word: "Filme", hint: "História em movimento" },
    { word: "Série", hint: "Narrativa contínua" },
    { word: "Documentário", hint: "Realidade editada" },
    { word: "Desenho animado", hint: "Infância compartilhada" },
    { word: "Anime", hint: "Estilo reconhecível" },
    { word: "HQ", hint: "Narrativa ilustrada" },
    { word: "Mangá", hint: "Leitura invertida" },
    { word: "Super-herói", hint: "Responsabilidade ampliada" },
    { word: "Vilão", hint: "Motiva o conflito" },
    { word: "Anti-herói", hint: "Moral flexível" },
    { word: "Personagem", hint: "Identidade fictícia" },
    { word: "Protagonista", hint: "Centro da história" },
    { word: "Antagonista", hint: "Força oposta" },
    { word: "Trilogia", hint: "História em partes" },
    { word: "Saga", hint: "Extensão narrativa" },
    { word: "Franquia", hint: "Marca recorrente" },
    { word: "Reboot", hint: "Recomeço conhecido" },
    { word: "Remake", hint: "Versão atualizada" },
    { word: "Spin-off", hint: "Desvio narrativo" },
    { word: "Crossover", hint: "Universos conectados" },
    { word: "Final surpresa", hint: "Quebra de expectativa" },
    { word: "Cliffhanger", hint: "Suspense forçado" },
    { word: "Spoiler", hint: "Informação indesejada" },
    { word: "Maratona", hint: "Consumo intenso" },
    { word: "Streaming", hint: "Disponibilidade imediata" },
    { word: "Blockbuster", hint: "Alto investimento" },
    { word: "Cena pós-créditos", hint: "Recompensa paciente" },
    { word: "Trailer", hint: "Promessa editada" },
    { word: "Teaser", hint: "Informação mínima" },
    { word: "Oscar", hint: "Reconhecimento simbólico" },
    { word: "Grammy", hint: "Prestígio musical" },
    { word: "Festival", hint: "Celebração cultural" },
    { word: "Show", hint: "Experiência coletiva" },
    { word: "Concerto", hint: "Execução precisa" },
    { word: "Clipe", hint: "Imagem musical" },
    { word: "Hit", hint: "Popularidade rápida" },
    { word: "Viral", hint: "Disseminação espontânea" },
    { word: "Meme", hint: "Humor replicável" },
    { word: "Trend", hint: "Atenção temporária" },
    { word: "Cosplay", hint: "Identidade emprestada" },
    { word: "Fandom", hint: "Comunidade dedicada" },
    { word: "Influencer", hint: "Autoridade informal" },
    { word: "Youtuber", hint: "Conteúdo pessoal" },
    { word: "Streamer", hint: "Presença ao vivo" },
    { word: "Podcast", hint: "Conversa gravada" },
    { word: "Talk show", hint: "Entrevista performática" },
    { word: "Reality show", hint: "Competição observada" },
    { word: "Talent show", hint: "Habilidade avaliada" },
    { word: "Game show", hint: "Regras claras" },
    { word: "Videogame", hint: "Interação ativa" },
    { word: "Console", hint: "Plataforma dedicada" },
    { word: "Controle", hint: "Decisão manual" },
    { word: "NPC", hint: "Presença programada" },
    { word: "Boss final", hint: "Desafio máximo" },
    { word: "Level", hint: "Progresso medido" },
    { word: "Skin", hint: "Mudança estética" },
    { word: "Loot", hint: "Recompensa aleatória" },
    { word: "Ranking", hint: "Comparação pública" },
    { word: "Campeonato", hint: "Competição formal" },
    { word: "E-sports", hint: "Profissionalização do jogo" },
    { word: "Live", hint: "Tempo real" },
    { word: "Plateia", hint: "Observadores ativos" },
    { word: "Fama", hint: "Reconhecimento amplo" },
    { word: "Celebridade", hint: "Exposição constante" },
    { word: "Ícone", hint: "Referência cultural" },
    { word: "Clássico", hint: "Resiste ao tempo" },
    { word: "Cult", hint: "Popularidade seletiva" }
  ]
},
Acoes: {
  label: "Ações",
  color: "#facc15",
  words: [
    { word: "Correr", hint: "Urgência em movimento" },
    { word: "Andar", hint: "Progresso constante" },
    { word: "Parar", hint: "Interrupção voluntária" },
    { word: "Esperar", hint: "Tempo sem controle" },
    { word: "Observar", hint: "Atenção silenciosa" },
    { word: "Olhar", hint: "Contato visual breve" },
    { word: "Enxergar", hint: "Compreensão além do óbvio" },
    { word: "Escutar", hint: "Atenção ativa" },
    { word: "Ouvir", hint: "Som recebido" },
    { word: "Falar", hint: "Ideia exposta" },
    { word: "Conversar", hint: "Troca equilibrada" },
    { word: "Gritar", hint: "Volume extremo" },
    { word: "Sussurrar", hint: "Segredo compartilhado" },
    { word: "Pensar", hint: "Processo interno" },
    { word: "Refletir", hint: "Pensamento aprofundado" },
    { word: "Decidir", hint: "Fim da dúvida" },
    { word: "Escolher", hint: "Comparação implícita" },
    { word: "Duvidar", hint: "Falta de certeza" },
    { word: "Confiar", hint: "Risco calculado" },
    { word: "Acreditar", hint: "Aceitação sem prova" },
    { word: "Criar", hint: "Trazer algo novo" },
    { word: "Construir", hint: "Progresso acumulado" },
    { word: "Destruir", hint: "Fim abrupto" },
    { word: "Quebrar", hint: "Perda de forma" },
    { word: "Arrumar", hint: "Organização ativa" },
    { word: "Bagunçar", hint: "Ordem invertida" },
    { word: "Limpar", hint: "Remover excessos" },
    { word: "Sujar", hint: "Estado alterado" },
    { word: "Cozinhar", hint: "Transformação controlada" },
    { word: "Comer", hint: "Ação básica" },
    { word: "Beber", hint: "Consumo direto" },
    { word: "Mastigar", hint: "Processo repetitivo" },
    { word: "Engolir", hint: "Ação final" },
    { word: "Dormir", hint: "Desligamento parcial" },
    { word: "Acordar", hint: "Retorno à consciência" },
    { word: "Sonhar", hint: "Realidade alternativa" },
    { word: "Trabalhar", hint: "Esforço contínuo" },
    { word: "Descansar", hint: "Recuperação necessária" },
    { word: "Viajar", hint: "Mudança de cenário" },
    { word: "Partir", hint: "Início da ausência" },
    { word: "Chegar", hint: "Fim do trajeto" },
    { word: "Entrar", hint: "Mudança de espaço" },
    { word: "Sair", hint: "Afastamento voluntário" },
    { word: "Abrir", hint: "Permitir acesso" },
    { word: "Fechar", hint: "Limitar passagem" },
    { word: "Guardar", hint: "Proteção futura" },
    { word: "Perder", hint: "Ausência sentida" },
    { word: "Encontrar", hint: "Fim da busca" },
    { word: "Buscar", hint: "Movimento intencional" },
    { word: "Procurar", hint: "Tentativa repetida" },
    { word: "Ajudar", hint: "Ação voltada ao outro" },
    { word: "Atrapalhar", hint: "Interferência negativa" },
    { word: "Ensinar", hint: "Compartilhar conhecimento" },
    { word: "Aprender", hint: "Aquisição contínua" },
    { word: "Treinar", hint: "Repetição com objetivo" },
    { word: "Competir", hint: "Comparação direta" },
    { word: "Ganhar", hint: "Resultado positivo" },
    { word: "Perder", hint: "Resultado negativo" },
    { word: "Arriscar", hint: "Possibilidade de falha" },
    { word: "Evitar", hint: "Desvio consciente" },
    { word: "Aceitar", hint: "Fim da resistência" },
    { word: "Recusar", hint: "Negação explícita" },
    { word: "Convidar", hint: "Abertura social" },
    { word: "Ignorar", hint: "Atenção negada" },
    { word: "Reagir", hint: "Resposta imediata" },
    { word: "Controlar", hint: "Manter limites" },
    { word: "Soltar", hint: "Liberação voluntária" },
    { word: "Segurar", hint: "Resistência física ou simbólica" }
  ]
},
QualidadesDefeitos: {
  label: "Qualidades / Defeitos",
  color: "#38bdf8",
  words: [
    { word: "Coragem", hint: "Avança apesar do medo" },
    { word: "Medo", hint: "Alerta exagerado" },
    { word: "Paciência", hint: "Tempo como aliado" },
    { word: "Impaciência", hint: "Urgência constante" },
    { word: "Honestidade", hint: "Transparência direta" },
    { word: "Mentira", hint: "Verdade adaptada" },
    { word: "Sinceridade", hint: "Fala sem filtro" },
    { word: "Hipocrisia", hint: "Discurso inconsistente" },
    { word: "Humildade", hint: "Consciência do limite" },
    { word: "Orgulho", hint: "Autoimagem elevada" },
    { word: "Generosidade", hint: "Compartilhamento espontâneo" },
    { word: "Egoísmo", hint: "Prioridade pessoal" },
    { word: "Empatia", hint: "Sentir com o outro" },
    { word: "Indiferença", hint: "Ausência de reação" },
    { word: "Lealdade", hint: "Constância relacional" },
    { word: "Traição", hint: "Quebra de confiança" },
    { word: "Confiança", hint: "Risco aceito" },
    { word: "Desconfiança", hint: "Cautela excessiva" },
    { word: "Disciplina", hint: "Ordem interna" },
    { word: "Desorganização", hint: "Caos recorrente" },
    { word: "Responsabilidade", hint: "Assumir consequências" },
    { word: "Imaturidade", hint: "Reação impulsiva" },
    { word: "Maturidade", hint: "Controle emocional" },
    { word: "Vaidade", hint: "Imagem valorizada" },
    { word: "Modéstia", hint: "Exposição reduzida" },
    { word: "Persistência", hint: "Insistência estratégica" },
    { word: "Teimosia", hint: "Insistência cega" },
    { word: "Criatividade", hint: "Soluções fora do padrão" },
    { word: "Rigidez", hint: "Pouca flexibilidade" },
    { word: "Flexibilidade", hint: "Adaptação rápida" },
    { word: "Controle", hint: "Necessidade de domínio" },
    { word: "Impulsividade", hint: "Ação sem cálculo" },
    { word: "Cautela", hint: "Ação medida" },
    { word: "Ansiedade", hint: "Futuro antecipado" },
    { word: "Calma", hint: "Estabilidade emocional" },
    { word: "Otimismo", hint: "Expectativa positiva" },
    { word: "Pessimismo", hint: "Expectativa negativa" },
    { word: "Confiança excessiva", hint: "Risco ignorado" },
    { word: "Autocrítica", hint: "Avaliação interna" },
    { word: "Autoconfiança", hint: "Certeza pessoal" },
    { word: "Insegurança", hint: "Dúvida constante" },
    { word: "Determinação", hint: "Objetivo fixo" },
    { word: "Acomodação", hint: "Esforço mínimo" },
    { word: "Ambição", hint: "Desejo de mais" },
    { word: "Conformismo", hint: "Aceitação passiva" },
    { word: "Resiliência", hint: "Retorno após impacto" },
    { word: "Fragilidade", hint: "Resposta intensa" },
    { word: "Sociabilidade", hint: "Interação fácil" },
    { word: "Timidez", hint: "Retração social" },
    { word: "Extroversão", hint: "Energia externa" },
    { word: "Introversão", hint: "Energia interna" },
    { word: "Autoridade", hint: "Influência natural" },
    { word: "Submissão", hint: "Aceitação do comando" },
    { word: "Liderança", hint: "Direção coletiva" },
    { word: "Passividade", hint: "Ausência de iniciativa" },
    { word: "Proatividade", hint: "Ação antecipada" },
    { word: "Arrogância", hint: "Superioridade declarada" },
    { word: "Simplicidade", hint: "Pouca complexidade" },
    { word: "Complexidade", hint: "Múltiplas camadas" },
    { word: "Transparência", hint: "Nada oculto" },
    { word: "Manipulação", hint: "Controle indireto" },
    { word: "Carisma", hint: "Atração natural" },
    { word: "Antipatia", hint: "Rejeição imediata" }
  ]
}
};
